all:
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT /projects/prospect/converted_data/Pulse_Latest/DryCommissioning/series010/s010_f00000_ts1515863915_Pulse.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT /projects/prospect/converted_data/Pulse_Latest/DryCommissioning/series010/s010_f00001_ts1515864283_Pulse.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT /projects/prospect/converted_data/Pulse_Latest/DryCommissioning/series010/s010_f00002_ts1515864650_Pulse.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT /projects/prospect/converted_data/Pulse_Latest/DryCommissioning/series010/s010_f00003_ts1515865237_Pulse.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT /projects/prospect/converted_data/Pulse_Latest/DryCommissioning/series010/s010_f00004_ts1515865656_Pulse.h5 ;
