# Change contents in "all:"
# For Contents under #Execute PulseCruncher use:
# <Location of PulseCruncher> <PulseCruncher Config File> <Location of InputFile> <Location of Waveform File> <Location to Output/Output File Name>
# For Concents under #Execute .h5 to .root convertor use:
# <Location of Convertor> <Location of .h5>
all:
	#Execute PulseCruncher
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00000_ts1515703143_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f0.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00001_ts1515703296_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f1.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00002_ts1515703430_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f2.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00003_ts1515703613_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f3.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00004_ts1515703783_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f4.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00005_ts1515703925_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f5.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00006_ts1515704107_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f6.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00007_ts1515704239_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f7.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00008_ts1515704389_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f8.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00009_ts1515704528_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f9.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00010_ts1515704665_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f10.h5;	
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00011_ts1515704828_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f11.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00012_ts1515704965_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f12.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00013_ts1515705292_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f13.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00014_ts1515705524_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f14.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00015_ts1515705777_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f15.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00016_ts1515706053_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f16.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00017_ts1515706250_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f17.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00018_ts1515706391_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f18.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00019_ts1515706567_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f19.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/PulseCruncher/./PulseCruncher ~/LightInjection-Analysis/GainAnalysis/LI_PulseCruncher.cfg /projects/prospect/converted_data/Unpacked/DryCommissioning/series005/s005_f00020_ts1515706708_Unpacked.root ~/LightInjection-Analysis/OCS/series005/s05_f20.h5;
	#Execute .h5 to .root convertor
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f0.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f1.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f2.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f3.h5; 
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f4.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f5.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f6.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f7.h5; 
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f8.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f9.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f10.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f11.h5; 
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f12.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f13.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f14.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f15.h5;       
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f16.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f17.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f18.h5;
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f19.h5; 
	~/MPMAnalysis/V5/PROSPECT2x_Analysis/Examples/./DetPulse_HDF5_to_ROOT ~/LightInjection-Analysis/OCS/series005/s05_f20.h5;

